# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-03 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_goods', '0005_auto_20180202_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lbsm', models.CharField(default='', max_length=20)),
                ('gpic', models.ImageField(upload_to='cl_goods')),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cl_goods.GoodInfo')),
            ],
        ),
    ]
