# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-04 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_goods', '0006_goodimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeinfo',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='typeinfo',
            name='turl',
            field=models.CharField(default='', max_length=64),
        ),
    ]
