# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-21 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_user', '0002_auto_20180120_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usex',
            field=models.CharField(default='', max_length=2),
        ),
    ]
